import { poppins } from './fonts'
import './globals.css'

export const metadata = {
 title: 'Hotel S Bocas',
 description: 'Generated by create next app',
}

const languages = ['en', 'es', 'fr']
const directions = { 'en': 'ltr', 'es': 'ltr', 'fr': 'ltr' } // Modify this as per your requirement

export async function getStaticPaths() {
 return {
   paths: languages.map((lng) => ({ params: { lng } })),
   fallback: false,
 };
}

export default function RootLayout({
 children,
 params: {
   lng
 }
}) {
 return (
   <html lang={lng} dir={directions[lng]}>
     <head />
     <body>
       {children}
     </body>
   </html>
 )
}
